---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: main
    # Remove the line above to run when pushing to master
  pull_request:
    branches: main

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      #   Checkout the code    #
      ##########################
      - name: Lint
        run: |
          yarn install
          yarn lint
          yarn run build
